targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          - lib/src/blocs/**/*.dart
          - lib/src/models/*.dart
          - test/freezed/*.dart
          - test/freezed/**/*.dart
      json_serializable:json_serializable:
        generate_for:
          - lib/src/models/*.dart
          - test/freezed/*.dart
          - test/freezed/**/*.dart
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # Default values
          #any_map: false
          #checked: false
          #create_factory: true
          #create_to_json: true
          #disallow_unrecognized_keys: false
          #explicit_to_json: false
          #field_rename: none
          #ignore_unannotated: false
          #include_if_null: true
          #nullable: true

          # Overridden values
          explicit_to_json: true
      mockito|mockBuilder:
        generate_for:
          - test/**/*_test.dart