name: checkin
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  firebase_crashlytics: ^2.0.1
  firebase_messaging: ^9.1.2
  firebase_dynamic_links: ^2.0.1
  firebase_storage: ^8.0.4
  firebase_analytics: ^8.0.1
  cloud_firestore: ^1.0.6
  cloud_functions: ^1.0.4
  google_sign_in: ^5.0.2
  http: ^0.13.1
  json_annotation: ^4.0.1
  cached_network_image: ^3.0.0
  image_picker: ^0.7.4
  flutter_svg: ^0.21.0+1
  shared_preferences: ^2.0.5
  rx_shared_preferences: 2.0.0-nullsafety.0
  google_fonts: ^2.0.0

  sign_in_with_apple: ^3.0.0
  share: ^2.0.1
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  fluro: ^2.0.3
  platform: ^3.0.0
  i18n_extension: ^4.0.3
  url_launcher: ^6.0.2
  table_calendar: ^2.3.3
  package_info: ^2.0.0
  open_appstore: ^1.0.2
  pub_semver: ^2.0.0
  image_cropper: ^1.4.0
  crypto: ^3.0.0
  open_mail_app: ^0.1.1
  logger: ^1.0.0
  uuid: ^3.0.4
  vector_math: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^5.0.5
  build_runner: ^1.12.2
  freezed: ^0.14.1+2
  json_serializable: ^4.1.1
  integration_test: ^1.0.2+3
  bloc_test: ^8.0.0
  mocktail: ^0.1.1
  stack_trace: ^1.10.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.5+1

dependency_overrides:
  intl: ^0.17.0
  analyzer: ^1.3.0
  test_api: 0.3.0
  args: 2.0.0

flutter_icons:
  image_path: "assets/launcher_icon/icon.png"
  adaptive_icon_foreground: "assets/launcher_icon/adaptive_icon.png"
  adaptive_icon_background: "#FF0024"
  ios: true
  android: true

flutter_native_splash:
  image: assets/splash/logo_light.png
  color: "#FF0024"
  image_dark: assets/splash/logo_dark.png
  color_dark: "#FF0024"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/splash/
    - assets/launcher_icon/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
          style: normal
        - asset: fonts/Raleway-LightItalic.ttf
          style: italic
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 700
