name: checkin
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.11.1+12
  firebase_core: ^0.4.0
  google_sign_in: ^4.0.1+1
  cloud_firestore: ^0.12.7+1
  rxdart: ^0.21.0
  bloc: ^0.12.0
  equatable: ^0.2.2
  flutter_bloc: ^0.11.0
  firebase_crashlytics: ^0.0.4+8
  firebase_messaging: ^5.1.2

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  mockito: ^3.0.0
  firebase: ^5.0.0
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  image_test_utils: ^1.0.0
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo-ios.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
