name: checkin
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_crashlytics: ^0.2.4
  firebase_messaging: ^7.0.3
  firebase_dynamic_links: ^0.5.0+9
  firebase_storage: ^4.0.1
  firebase_analytics: ^5.0.15
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.6.0+1
  google_sign_in: ^4.5.1
  sign_in_with_apple: ^2.5.4
  share: ^0.6.3+5
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1
  equatable: ^1.1.1
  cached_network_image: ^2.3.3
  fluro: ^1.7.8
  platform: ^3.0.0-nullsafety.4
  json_annotation: ^3.1.1
  i18n_extension: 3.0.0-dev.1
  url_launcher: ^5.4.1
  table_calendar: ^2.3.3
  flutter_svg: ^0.20.0-nullsafety.3
  package_info: ^0.4.0+14
  open_appstore: ^1.0.2
  pub_semver: ^1.4.4
  image_cropper: ^1.2.3
  image_picker: ^0.6.7+1
  crypto: ^2.1.5
  http: ^0.12.1
  shared_preferences: ^0.5.12+4
  rx_shared_preferences: ^1.3.3
  open_mail_app: ^0.0.6
  google_fonts: ^1.1.1
  logger: ^0.9.4

dev_dependencies:
  test: ">=1.5.0 <3.0.0"
  mockito: 4.1.3
  bloc_test: ^7.1.0
  # TODO: this has conflicts with flutter_svg
#  flutter_launcher_icons: ^0.8.1
#  flutter_native_splash: ^0.3.0
  stack_trace: ^1.9.3
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^1.10.6
  freezed: ^0.12.3
  json_serializable: ^3.5.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2


flutter_icons:
  image_path: "assets/launcher_icon/icon.png"
  adaptive_icon_foreground: "assets/launcher_icon/adaptive_icon.png"
  adaptive_icon_background: "#FF0024"
  ios: true
  android: true

flutter_native_splash:
  image: assets/splash/logo_light.png
  color: "#FF0024"
  image_dark: assets/splash/logo_dark.png
  color_dark: "#FF0024"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/splash/
    - assets/launcher_icon/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
          style: normal
        - asset: fonts/Raleway-LightItalic.ttf
          style: italic
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 700
